# Part 2 — Introduction to NumPy

In this section, we begin working with **NumPy**, the fundamental package for numerical computing in Python.

NumPy provides:

- Fast numerical arrays
- Mathematical operations on entire datasets
- Linear algebra functionality
- Random number generation

Most scientific and data science libraries in Python are built on top of NumPy.

---

## Importing NumPy

By convention, NumPy is imported using the alias `np`.

In [1]:
import numpy as np

---

# 1. Creating NumPy Arrays

The core object in NumPy is the **ndarray** (n-dimensional array).

Unlike Python lists, NumPy arrays:

- Are stored more efficiently in memory
- Support vectorized operations
- Allow fast numerical computation

---

## Creating an Array from a List

In [8]:
lst = [1, 2, 3, 4, 5]
a = np.array(lst)
print(f"lst = {lst}")
print(f"arr = {a}")

lst = [1, 2, 3, 4, 5]
arr = [1 2 3 4 5]


Notice that the output does not contain commas.  
This indicates it is a NumPy array, not a regular Python list.

---

## Checking the Type

In [9]:
type(a)

numpy.ndarray

---

# 2. Array Properties

NumPy arrays have useful attributes.

In [10]:
print("Shape:", a.shape)
print("Data type:", a.dtype)
print("Number of dimensions:", a.ndim)
print("Number of elements:", a.size)

Shape: (5,)
Data type: int32
Number of dimensions: 1
Number of elements: 5


---

# 3. Creating Special Arrays

NumPy provides helper functions for common array types.

In [11]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)

zeros, ones, identity

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

---

# 4. Generating Sequences

In [12]:
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


- `arange(start, stop, step)` works like Python's range
- `linspace(start, stop, num_points)` creates evenly spaced values

---

# 5. Basic Arithmetic (Vectorized Operations)

One of NumPy’s biggest advantages is vectorization.

Operations are applied element-wise.

In [13]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

x + y

array([11, 22, 33])

In [14]:
x * y

array([10, 40, 90])

This is much faster and cleaner than writing loops.

---

# 6. Aggregations

In [15]:
data = np.array([3, 7, 2, 9, 4])

print("Mean:", np.mean(data))
print("Standard deviation:", np.std(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Sum:", np.sum(data))

Mean: 5.0
Standard deviation: 2.6076809620810595
Minimum: 2
Maximum: 9
Sum: 25


---

# 7. Indexing and Slicing

In [16]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr[0]

0

In [18]:
arr[2:6]

array([2, 3, 4, 5])

NumPy slicing behaves similarly to Python slicing but works efficiently on large datasets.

---

# 8. 2D Arrays

In [19]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matrix.shape

(3, 3)

In [21]:
matrix[0, 1]

2

Rows come first, columns second: `[row, column]`.

---

# Exercise Section

Try the following:

1. Create an array containing the numbers 1 to 20.
2. Reshape it into a 4 × 5 matrix. (Hint: use the `reshape` method.)
3. Compute:
   - The mean of the entire array
   - The mean of each row
   - The mean of each column
4. Extract the third row.
5. Extract the last two columns.

You should not use loops.

---

In the next section, we will move from raw numerical arrays to structured tabular data using Pandas.

In [ ]:
# Your code goes here